openapi: "3.0.0"
info:
  version: 1.0.0
  title: Minimal ping API server
paths:
  /ping:
    get:
      responses:
        '200':
          description: pint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
  /xtz/delegations:
    get:
      parameters:
        - name: year
          in: query
          schema:
            type: integer
            format: uint32
            example: 2024
      responses:
        '200':
          description: delegation listing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DelegationsListing'
        '500':
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    # base types
    Pong:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong
    DelegationsListing:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items: 
            $ref: '#/components/schemas/Delegation'
    Delegation:
      type: object
      required:
        - timestamp
        - amount
        - delegator
        - level
      properties:
        timestamp:
          type: string
        amount:
          type: string
        delegator:
          type: string
        level:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string